EcommerceApplication/Authentication/urls.py
from django.urls import path
from . import views

app_name = 'Authentication'

urlpatterns = [
    path('logout', views.custom_logout, name='custom_logout')
]

EcommerceApplication/Core/urls.py
from django.urls import path
from .import views

app_name = 'Core'
urlpatterns = [
    path('', views.main, name='main'),
    path('products', views.ProductsListView.as_view(), name='productslistview'),
    path('detailview/<slug>/', views.ItemDetailView.as_view(), name='itemdetailview'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('order-summary', views.OrderSummaryView.as_view(), name='order-summary'),
    path('checkout', views.CheckoutView.as_view(), name='checkout'),
    path('customer-details', views.customer_details_view, name="customer-details-view"),
    path('help/order-placement', views.help_orderplacement, name="help-orderplacement"),
    path('help/payments', views.help_payments, name='help-payments'),
    path('help/returns', views.help_returns, name="help-returns"),
    path('size-chart' ,views.size_chart, name='size-chart'),
]

EcommerceApplication/EcommerceProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('Authentication.urls', namespace = 'Authentication')),
    path('', include('Core.urls', namespace = 'Core'))
]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

EcommerceApplication/templates/checkout.html
{% load static %}
{% load cart_template_tag %}
<!DOCTYPE html>
<html>
<head>
    <head>
        <meta name="viewport" width=device-width, initial scale=1.0>
        <title>products detail view</title>
        <link rel="stylesheet" href="{% static 'cart-order.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.jss">
        <script src="{% static 'index.js' %}" defer></script>
    </head>
</head>
<body>
    <section class="main">
    <nav>
        <div class="logo">
            <p id="ttl">AFRIC<span style="color: #000;">ANA</span><i class="fa fa-leaf"></i></p>
        </div>
        </div>
        <div class="nav-links">
            <ul>
                <li><a href="{% url 'Core:main' %}">Home</a></li>
                <li><a href="{% url 'Core:productslistview' %}">Products</a></li>
                {% if user.is_authenticated %}
                    <li class="acc"><div class="inside-li"><i class="fa fa-user" id="fauser"></i><a href="about.html">Hi, {{user.username}}</a><i class="fa fa-chevron-down" id="fadown1"></i></div>
                    <div class="acc-submenu">
                        <ul>
                            <li><a href="">My Account</a></li>
                            <li><a href="">Orders</a></li>
                            <li><a href="">Saved Items</a></li>
                            <li><a href="{% url 'Authentication:custom_logout' %}">Log Out</a></li>
                
                        </ul>
                    </div>
                </li>
                {% else %}
                    <li class="acc"><div class="inside-li"><i class="fa fa-user" id="fauser"></i><a href="about.html">Account</a><i class="fa fa-chevron-down" id="fadown1"></i></div>
                        <div class="acc-submenu">
                            <ul>
                                <li><a href="">My Account</a></li>
                                <li><a href="">Orders</a></li>
                                <li><a href="">Saved Items</a></li>
                                <li><a href="{% url 'account_login' %}">Sign In</a></li>
                    
                            </ul>
                        </div>
                    </li>
                {% endif %}
                <li class="acc"><div class="inside-li"><i class="fa fa-question-circle" id="fahelp"></i><a href="contact.html">Help</a><i class="fa fa-chevron-down" id="fadown2"></i></div>
                    <div class="acc-submenu" id="submenu-2">
                        <ul>
                            <li><a href="{% url 'Core:help-orderplacement' %}">Placing an Order</a></li>
                            <li><a href="{% url 'Core:help-payments' %}">Payments</a></li>
                            <li><a href="{% url 'Core:help-returns' %}">Return and Refunds</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="{% url 'Core:order-summary' %}"></a><span class="count-badge">{{ request.user|cart_item_count }}</span><i class="fa fa-shopping-cart" id="facart"></i>Cart</li>
                </ul>
        </div>
    </nav>
    {% if customer_details %}
        <section class="checkout">
            
            <form id="checkout-form" method="POST" action="{% url 'Core:checkout'%}">
                {% csrf_token %}
                <div class="flex-box">
                    <div class="chkout-box">
                        <div class="cbox">
                            <div class="mini-fbox">
                                <div><h4>Customer Address</h4></div>
                                <div><a id="anchor1" href="{% url 'Core:customer-details-view' %}">Change<i id="chv-right" class="fa fa-chevron-right"></i></a></div>
                            </div>
                            <p>{{ customer_details.first_name }} {{ customer_details.surname}}</p>
                            <p style="margin-top: 10px;">{{ customer_details.country }} | {{ customer_details.town }} | {{ customer_details.phone_number }}
                        </div>
                        <div class="cbox">
                            <div class="mini-fbox">
                                <div><h4>Delivery Details</h4></div>
                                <div><a id="anchor2" href="{% url 'Core:customer-details-view' %}">Change<i id="chv-right" class="fa fa-chevron-right"></i></a></div>
                            </div>
                            <p>Pick-up Station</p>
                            <p>{{ customer_details.pickup_station }}</p>
                        </div>
                        <div class="cbox">
                            <h4>Payment Method</h4>
                            <input type="radio" id="mpesa" name="payment_method" value="mpesa">
                            <label for="mpesa">M-Pesa</label>
                            <br>
                            <input type="radio" id="paypal" name="payment_method" value="paypal">
                            <label for="paypal">PayPal</label>
                        </div>

                    </div>
                    <div class="chkout-box" id="chk-cart">
                        <div class="mini-fbox">
                            <div><h4>Your Cart</h4></div>
                            <div><span class="cart-count2">{{ request.user|cart_item_count }}</div>
                        </div>
                        <div class="chkcart">
                            <table>
                                <thead>
                                    <tr>
                                        <th scope="col">Item title</th>
                                        <th scope="col">Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order_item in object.items.all %}
                                    <tr>
                                        <td>{{order_item.item.title}}</td>
                                        <td>Ksh. {{order_item.item.price}}</td>
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <td><b>Order Total</b></td>
                                        <td colspan="1">Ksh. {{object.get_total}}</td>

                                    </tr>
                            </table>

                            
                        </div>
                        <div class="checkout-btns">
                            <button id="chk-btn1">Modify Cart</button>
                            <button type="submit" id="chk-btn2" >Confirm Order</button>
                        </div>
                    </div>
                </div>
        </form>
        </section>

        {% else %}
        <div class="chk-alt-content">
            <p> Customer details not found. Please complete<br> your profile before placing your order.</p>
            <a href="{% url 'Core:customer-details-view' %}"><button id="alt-content-btn">Complete Profile</button></a>
        </div>
        {% endif %}
        
        </section>
    <!--footer-->
    <section class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col-1">
            <h3>Download Our App</h3>
            <p>Download App for Android and IOS mobile phone.</p>
                <div class="app-logo">
                    <img src="{% static 'images/play-store.png' %}">
                    <img src="{% static 'images/app-store.png' %}">
                </div>
            
            </div>
            <div class="footer-col-2">
                <p id="ttl2">AFRIC<span style="color: #fff;">ANA</span><i class="fa fa-leaf"></i></p>
                <p> We ensure you are connected to the future with just a click.<br> Shop with us to stay connected.</p>
            </div>
            <div class="footer-col-3">
            <h3>Useful Links</h3>
            <ul>
                <li>Coupons</li>
                <li>Blog Post</li>
                <li>Return Policy</li>
                <li>Join Affiliate</li>
            </ul>
            </div>
             <div class="footer-col-4">
            <h3>Follow us</h3>
            <ul>
                <li>Facebook</li>
                <li>X</li>
                <li>Instagram</li>
                <li>Youtube</li>
            </ul>
            </div>
            
        </div>
        <hr>
        <p class="copyright">Copyright 2023 - Lenny B</p>
        
    
    </div>
    </section>
    
</body>
</html>

EcommerceApplication/templates/customerdetails.html
{% load static %}
{% load cart_template_tag %}
<!DOCTYPE html>
<html>
<head>
    <head>
        <meta name="viewport" width=device-width, initial scale=1.0>
        <title>products detail view</title>
        <link rel="stylesheet" href="{% static 'cart-order.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.jss">
        <script src="{% static 'index.js' %}" defer></script>
    </head>
</head>
<body>
    <section class="main">
    <nav>
        <div class="logo">
            <p id="ttl">AFRIC<span style="color: #000;">ANA</span><i class="fa fa-leaf"></i></p>
        </div>
        </div>
        <div class="nav-links">
            <ul>
                <li><a href="{% url 'Core:main' %}">Home</a></li>
                <li><a href="{% url 'Core:productslistview' %}">Products</a></li>
                {% if user.is_authenticated %}
                    <li class="acc"><div class="inside-li"><i class="fa fa-user" id="fauser"></i><a href="about.html">Hi, {{user.username}}</a><i class="fa fa-chevron-down" id="fadown1"></i></div>
                    <div class="acc-submenu">
                        <ul>
                            <li><a href="">My Account</a></li>
                            <li><a href="">Orders</a></li>
                            <li><a href="">Saved Items</a></li>
                            <li><a href="{% url 'Authentication:custom_logout' %}">Log Out</a></li>
                
                        </ul>
                    </div>
                </li>
                {% else %}
                    <li class="acc"><div class="inside-li"><i class="fa fa-user" id="fauser"></i><a href="about.html">Account</a><i class="fa fa-chevron-down" id="fadown1"></i></div>
                        <div class="acc-submenu">
                            <ul>
                                <li><a href="">My Account</a></li>
                                <li><a href="">Orders</a></li>
                                <li><a href="">Saved Items</a></li>
                                <li><a href="{% url 'account_login' %}">Sign In</a></li>
                    
                            </ul>
                        </div>
                    </li>
                {% endif %}
                <li class="acc"><div class="inside-li"><i class="fa fa-question-circle" id="fahelp"></i><a href="contact.html">Help</a><i class="fa fa-chevron-down" id="fadown2"></i></div>
                    <div class="acc-submenu" id="submenu-2">
                        <ul>
                            <li><a href="{% url 'Core:help-orderplacement' %}">Placing an Order</a></li>
                            <li><a href="{% url 'Core:help-payments' %}">Payments</a></li>
                            <li><a href="{% url 'Core:help-returns' %}">Return and Refunds</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="{% url 'Core:order-summary' %}"></a><span class="count-badge">{{ request.user|cart_item_count }}</span><i class="fa fa-shopping-cart" id="facart"></i>Cart</li>
                </ul>
        </div>
    </nav>
    <section class="customer-details">
        <form method="POST" action="{% url 'Core:customer-details-view' %}">
            {% csrf_token %}
            <div class="detailbox">
                <h4>Personal Details</h4>
                <label for="first_name">First Name</label>
                <input type="text" name="first_name" id="first_name"><br>
            
                <label for="surname">Surname</label>
                <input type="text" id="surname" name="surname"><br>
            
                <label for="country">Country</label>
                <select id="country" name="country">
                    <option value="">Select Country</option>
                    {% for code, name in countries %}
                        <option value="{{ code }}">{{ name }}</option>
                    {% endfor %}
                </select><br>
            
                <label for="phone_number">Phone Number</label>
                <input type="number" id="phone_number" name="phone_number" maxlength="10"><br>
            </div>
            <div class="detailbox" id="dbox2">
                <h4>Delivery Address</h4>
                <label for="town">Town</label>
                <input type="text" id="town" name="town"><br>
            
                <label for="pickup_station">Pickup Station</label>
                <select id="pickup_station" name="pickup_station">
                    <option>Kakamega Cossim Station</option>
                    <option>Mega-City Kisumu</option>
                    <option>Mbale-Pickup Station</option>
                </select><br>
            </div>
        
            <button id="cdetail-btn" type="submit">Save</button>
        </form>
        
    </section>
    
    </section>
    <!--footer-->
    <section class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col-1">
            <h3>Download Our App</h3>
            <p>Download App for Android and IOS mobile phone.</p>
                <div class="app-logo">
                    <img src="{% static 'images/play-store.png' %}">
                    <img src="{% static 'images/app-store.png' %}">
                </div>
            
            </div>
            <div class="footer-col-2">
                <p id="ttl2">AFRIC<span style="color: #fff;">ANA</span><i class="fa fa-leaf"></i></p>
                <p> We ensure you are connected to the future with just a click.<br> Shop with us to stay connected.</p>
            </div>
            <div class="footer-col-3">
            <h3>Useful Links</h3>
            <ul>
                <li>Coupons</li>
                <li>Blog Post</li>
                <li>Return Policy</li>
                <li>Join Affiliate</li>
            </ul>
            </div>
             <div class="footer-col-4">
            <h3>Follow us</h3>
            <ul>
                <li>Facebook</li>
                <li>X</li>
                <li>Instagram</li>
                <li>Youtube</li>
            </ul>
            </div>
            
        </div>
        <hr>
        <p class="copyright">Copyright 2023 - Lenny B</p>
        
    
    </div>
    </section>
    
</body>
</html>

EcommerceApplication/templates/detailview.html
{% load static %}
{% load cart_template_tag %}
<!DOCTYPE html>
<html>
<head>
    <head>
        <meta name="viewport" width=device-width, initial scale=1.0>
        <title>products detail view</title>
        <link rel="stylesheet" href="{% static 'cart-order.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.jss">
        <script src="{% static 'index.js' %}" defer></script>
    </head>
</head>
<body>
    <section class="main">
    <nav>
        <div class="logo">
            <p id="ttl">AFRIC<span style="color: #000;">ANA</span><i class="fa fa-leaf"></i></p>
        </div>
        </div>
        <div class="nav-links">
            <ul>
                <li><a href="{% url 'Core:main' %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li class="acc"><div class="inside-li"><i class="fa fa-user" id="fauser"></i><a href="about.html">Hi, {{user.username}}</a><i class="fa fa-chevron-down" id="fadown1"></i></div>
                        <div class="acc-submenu">
                            <ul>
                                <li><a href="">My Account</a></li>
                                <li><a href="">Orders</a></li>
                                <li><a href="">Saved Items</a></li>
                                <li><a href="{% url 'Authentication:custom_logout' %}">Log Out</a></li>
                    
                            </ul>
                        </div>
                </li>
                {% else %}
                    <li class="acc"><div class="inside-li"><i class="fa fa-user" id="fauser"></i><a href="about.html">Account</a><i class="fa fa-chevron-down" id="fadown1"></i></div>
                        <div class="acc-submenu">
                            <ul>
                                <li><a href="">My Account</a></li>
                                <li><a href="">Orders</a></li>
                                <li><a href="">Saved Items</a></li>
                                <li><a href="{% url 'account_login' %}">Sign In</a></li>
                    
                            </ul>
                        </div>
                    </li>
                {% endif %}
                <li class="acc"><div class="inside-li"><i class="fa fa-question-circle" id="fahelp"></i><a href="contact.html">Help</a><i class="fa fa-chevron-down" id="fadown2"></i></div>
                    <div class="acc-submenu" id="submenu-2">
                        <ul>
                            <li><a href="{% url 'Core:help-orderplacement' %}">Placing an Order</a></li>
                            <li><a href="{% url 'Core:help-payments' %}">Payments</a></li>
                            <li><a href="{% url 'Core:help-returns' %}">Return and Refunds</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="{% url 'Core:order-summary' %}"><span class="count-badge">{{ request.user|cart_item_count }}</span><i class="fa fa-shopping-cart" id="facart"></i>Cart</a></li>
                </ul>
        </div>
    </nav>
    <div class="cart-msg">
        {% if messages %}
         <div class="container">
            {% for message in messages %}
                <div class="alert">
                    {{ message }}
                    <button type="button" class="close-button" onclick="dismissMessage(this)">
                        <i class="fa fa-times"></i>
                    </button>
                </div>
            {% endfor %}
         </div>
        {% endif %}
    </div>
    
    <section class="detail-window">
        <div class="col-2">
            <img src="{{object.item_image.url}}">
            <div class="image-box">
                <div class="col-3">
                    <img src="{{ object.descimage1.url }}">
                </div>
                <div class="col-3">
                    <img src="{{ object.descimage2.url }}">
                </div>
                <div class="col-3">
                    <img src="{{ object.descimage3.url }}">
                </div>
            </div>
        </div>
        <div class="col-2" id="desc">
            <h4>{{object.title}}</h4>
            <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
                
            </div>
            <p>Ksh {{object.price}}</p>
    
            <form method="POST" action="{% url 'Core:add-to-cart' object.slug %}"> 
                {% csrf_token %}
            <div class="cart-box">
                <div class="add-cart">
                    <input type="number" name="quantity" maxlength="2">
                </div>
                <div class="add-cart">
                    <a href="{{ object.get_add_to_cart_url }}"><button type="submit" id="cart-btn">Add To Cart</button></a>
                </div>
                <div class="remove-cart">
                    <a href="{{ object.get_remove_from_cart_url }}"><button type="button" id="remove-cart-btn">Remove From Cart</button></a>
                </div>
            </div>

            {% if object.item_category == 'clothing&footwear' %}
            <div class="size-guide">
                <p>Ultimate Size Guide</p>
                <div class="sg-row">
                    <div class="sg-a">
                        <select name="size">
                            <option>S</option>
                            <option>M</option>
                            <option>X</option>
                            <option>XL</option>
                            <option>2XL</option>
                            <option>3XL</option>
                        </select>
                    </div>
                    <div class="sg-b">
                        <select name="size-category">
                            <option>Adult</option>
                            <option>Child</option>
                        </select>
                    </div>
                </div>
                <a href="{% url 'Core:size-chart' %}"><button type="button" id="sg-btn">View Size Chart</button></a>
            </div>
            {% endif %}
            </form>
        
            <h5>Product Description</h5>
            <p class="item-desc">{{ object.description }}</p>

            
        </div>
    </section>
    </section>
    <!--footer-->
    <section class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col-1">
            <h3>Download Our App</h3>
            <p>Download App for Android and IOS mobile phone.</p>
                <div class="app-logo">
                    <img src="{% static 'images/play-store.png' %}">
                    <img src="{% static 'images/app-store.png' %}">
                </div>
            
            </div>
            <div class="footer-col-2">
                <p id="ttl2">AFRIC<span style="color: #fff;">ANA</span><i class="fa fa-leaf"></i></p>
                <p> We ensure you are connected to the future with just a click.<br> Shop with us to stay connected.</p>
            </div>
            <div class="footer-col-3">
            <h3>Useful Links</h3>
            <ul>
                <li>Coupons</li>
                <li>Blog Post</li>
                <li>Return Policy</li>
                <li>Join Affiliate</li>
            </ul>
            </div>
             <div class="footer-col-4">
            <h3>Follow us</h3>
            <ul>
                <li>Facebook</li>
                <li>X</li>
                <li>Instagram</li>
                <li>Youtube</li>
            </ul>
            </div>
            
        </div>
        <hr>
        <p class="copyright">Copyright 2023 - Lenny B</p>
        
    
    </div>
    </section>
    
</body>
</html>
              

EcommerceApplication/templates/mpesa.html
<h5> Your payment via M-pesa is being processed<h5>
<p>{ message } </p>

EcommerceApplication/templates/paypal.html
<h5> Your paypament via PayPal is being processed</h5>
<p>Please wait ...</p>